version: '3'

services:
  db:
    image: mariadb
    restart: on-failure
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_USER: user001
      MYSQL_PASSWORD: j2FvHyzkZ3FJwHJU
      MYSQL_DATABASE: descargador
      MYSQL_ROOT_PASSWORD: j2FvHyzkZ3FJwHJU
    volumes:
      - ./mariadb:/var/lib/mysql
  broker:
    image: redis
    restart: on-failure
  worker:
    restart: on-failure
    command: celery worker -A descargador -l info --concurrency=1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - broker
    volumes:
      - .:/var/www/descargador  
  web:
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    depends_on:
      - db
      - broker
    ports:
      - "8007:8000"
    volumes:
      - .:/var/www/descargador
