version: '3.7'

services:
  db:
    image: mariadb
    restart: on-failure
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_USER: user001
      MYSQL_PASSWORD: j2FvHyzkZ3FJwHJU
      MYSQL_DATABASE: descargador
      MYSQL_ROOT_PASSWORD: j2FvHyzkZ3FJwHJU
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql

  broker:
    image: redis
    restart: on-failure

  worker:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile_Worker
    depends_on:
      - db
      - broker
    volumes:
      - .:/var/www/descargador

  web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile_Web
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/descargador
