version: '3'

services:
  db:
    image: mariadb:10.3.14
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: descargador
      MYSQL_ROOT_PASSWORD: j2FvHyzkZ3FJwHJU
    volumes:
      - ./mariadb:/var/lib/mysql
  
  broker:
    image: redis:5.0.4
    restart: always
  
  worker:
    restart: always
    command: celery worker -A descargador -l info --concurrency=1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - broker
    volumes:
      - ./media:/usr/src/app/media
    environment:
      - DEBUG=False
  
  beat:
    restart: always
    command: celery beat -A descargador -l info --pidfile=/opt/celeryd.pid --scheduler django_celery_beat.schedulers:DatabaseScheduler
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - broker
    volumes:
      - ./media:/usr/src/app/media
    environment:
      - DEBUG=False
  
  web:
    restart: always
    command: uwsgi --module=descargador.wsgi:application --master --http :8000 --vacuum
    build: .
    depends_on:
      - db
      - broker
    volumes:
      - ./media:/usr/src/app/media
      - ./staticfiles:/usr/src/app/staticfiles
    environment:
      - DEBUG=False
  
  webserver:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/usr/share/nginx/descargador    