version: '3'

services:
  db:
    image: mariadb:10.3.14    
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: descargador
      MYSQL_ROOT_PASSWORD: j2FvHyzkZ3FJwHJU
    volumes:
      - ./mariadb:/var/lib/mysql
  
  broker:
    image: redis:5.0.4    
  
  worker:    
    command: celery worker -A descargador -l info --concurrency=1
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - broker
    volumes:
      - ./media:/usr/src/app/media
    environment:
      - DEBUG=True
  
  beat:    
    command: celery beat -A descargador -l info --pidfile=/opt/celeryd.pid --scheduler django_celery_beat.schedulers:DatabaseScheduler
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - broker
    volumes:
      - ./media:/usr/src/app/media
    environment:
      - DEBUG=True

  web:    
    command: python manage.py runserver 0.0.0.0:8000
    build: .
    depends_on:
      - db
      - broker
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app/
    environment:
      - DEBUG=True